site_name: Панфилова Анна Константиновна
site_url: https://твой-сайт.ru
nav:
  - Об авторе: index.md
  - Лабораторная работа 1: labs/Laba_1.md
  - Лабораторная работа 2: labs/Laba_2.md
  - Лабораторная работа 3: labs/Laba_3.md
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.copy
  font:
    text: Roboto
    code: Fira Code

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/твой-профиль
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/твой-профиль
    - icon: fontawesome/brands/telegram
      link: https://t.me/твой-ник

extra_css:
  - stylesheets/extra.css